-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'e6380f4f0d7fca1f' HASH 'b78a0cfec575e96f45a41e178ed1ce2cb33435f0979358ee56c744c8653b3dd7' ADMIN;         
CREATE SEQUENCE "PUBLIC"."GEN" START WITH 1 RESTART WITH 1024 INCREMENT BY 50;
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_MESSAGE"(
    "RN_" INTEGER NOT NULL,
    "DATE_READ" TIMESTAMP(6),
    "DATE_SENT" TIMESTAMP(6),
    "ID" BIGINT,
    "RECIPIENT_ID" BIGINT,
    "SENDER_ID" BIGINT,
    "TEXT" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."HTE_MESSAGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_MESSAGE;             
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_TORNEO"(
    "HORA_FIN" TIME(6),
    "HORA_INICIO" TIME(6),
    "NUM_PARTICIPANTES" INTEGER,
    "PUNTOS" INTEGER,
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "GANADOR" CHARACTER VARYING(255),
    "NOMBRE" CHARACTER VARYING(255),
    "ESTADO" ENUM('Cerrado', 'En_espera')
); 
ALTER TABLE "PUBLIC"."HTE_TORNEO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_TORNEO;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_USUARIO_NUEVO"(
    "BANEADO" TINYINT,
    "ENABLED" BOOLEAN,
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    U&"CONTRASE\00d1A" CHARACTER VARYING(255),
    "CORREO" CHARACTER VARYING(255),
    "NOMBRE_USUARIO" CHARACTER VARYING(255),
    "PAIS" CHARACTER VARYING(255),
    "ROL" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."HTE_USUARIO_NUEVO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("RN_");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_USUARIO_NUEVO;       
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_PARTIDA"(
    "COLOR_TURNO" TINYINT,
    "ESTADO" TINYINT,
    "JUGADORES_MAX" INTEGER,
    "NUM_JUGADORES" INTEGER,
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "ID_TORNEO" BIGINT,
    "MOVIMIENTOS_TURNO" CHARACTER VARYING(255),
    "RESULTADO_FINAL" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."HTE_PARTIDA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_PARTIDA;             
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_USUARIO"(
    "ENABLED" BOOLEAN,
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "COLOR_FAVORITO" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "ROLES" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."HTE_USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_USUARIO;             
CREATE MEMORY TABLE "PUBLIC"."MESSAGE"(
    "DATE_READ" TIMESTAMP(6),
    "DATE_SENT" TIMESTAMP(6),
    "ID" BIGINT NOT NULL,
    "RECIPIENT_ID" BIGINT,
    "SENDER_ID" BIGINT,
    "TEXT" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."MESSAGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MESSAGE; 
CREATE MEMORY TABLE "PUBLIC"."PARTIDA"(
    "COLOR_TURNO" TINYINT,
    "ESTADO" TINYINT NOT NULL,
    "JUGADORES_MAX" INTEGER,
    "NUM_JUGADORES" INTEGER,
    "ID" BIGINT NOT NULL,
    "ID_TORNEO" BIGINT NOT NULL,
    "MOVIMIENTOS_TURNO" CHARACTER VARYING(255),
    "RESULTADO_FINAL" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."PARTIDA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB88" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTIDA; 
CREATE MEMORY TABLE "PUBLIC"."TORNEO"(
    "HORA_FIN" TIME(6),
    "HORA_INICIO" TIME(6),
    "NUM_PARTICIPANTES" INTEGER NOT NULL,
    "PUNTOS" INTEGER,
    "ID" BIGINT NOT NULL,
    "GANADOR" CHARACTER VARYING(255),
    "NOMBRE" CHARACTER VARYING(255) NOT NULL,
    "ESTADO" ENUM('Cerrado', 'En_espera') NOT NULL
);        
ALTER TABLE "PUBLIC"."TORNEO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_93" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TORNEO;  
CREATE MEMORY TABLE "PUBLIC"."USUARIO"(
    "ENABLED" BOOLEAN NOT NULL,
    "ID" BIGINT NOT NULL,
    "COLOR_FAVORITO" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLES" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_22" PRIMARY KEY("ID");     
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
INSERT INTO "PUBLIC"."USUARIO" VALUES
(TRUE, 1, NULL, NULL, NULL, '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W', 'ADMIN,USER', 'a'),
(TRUE, 2, NULL, NULL, NULL, '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W', 'USER', 'b'),
(TRUE, 3, NULL, NULL, NULL, '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W', 'USER', 'c');          
CREATE MEMORY TABLE "PUBLIC"."USUARIO_NUEVO"(
    "BANEADO" TINYINT,
    "ENABLED" BOOLEAN NOT NULL,
    "ID" BIGINT NOT NULL,
    U&"CONTRASE\00d1A" CHARACTER VARYING(255) NOT NULL,
    "CORREO" CHARACTER VARYING(255),
    "NOMBRE_USUARIO" CHARACTER VARYING(255) NOT NULL,
    "PAIS" CHARACTER VARYING(255),
    "ROL" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."USUARIO_NUEVO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3D6" PRIMARY KEY("ID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO_NUEVO;           
ALTER TABLE "PUBLIC"."PARTIDA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB8" CHECK("ESTADO" BETWEEN 0 AND 2) NOCHECK;              
ALTER TABLE "PUBLIC"."USUARIO_NUEVO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" CHECK("BANEADO" BETWEEN 0 AND 1) NOCHECK;         
ALTER TABLE "PUBLIC"."PARTIDA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB" CHECK("COLOR_TURNO" BETWEEN 0 AND 5) NOCHECK;          
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" UNIQUE NULLS DISTINCT ("USERNAME");     
ALTER TABLE "PUBLIC"."USUARIO_NUEVO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3D" UNIQUE NULLS DISTINCT ("NOMBRE_USUARIO");        
ALTER TABLE "PUBLIC"."MESSAGE" ADD CONSTRAINT "PUBLIC"."FKRROICXDT6QDA1CV1OXVSTPKEX" FOREIGN KEY("RECIPIENT_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."PARTIDA" ADD CONSTRAINT "PUBLIC"."FK2I3DWNYBT800FKR4ADQUGXOU8" FOREIGN KEY("ID_TORNEO") REFERENCES "PUBLIC"."TORNEO"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."MESSAGE" ADD CONSTRAINT "PUBLIC"."FK8C7M1J62DTM6GH5V08FNMWGLJ" FOREIGN KEY("SENDER_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;    
